name: hello-CICD-class-2025
on: push
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: step-one
        run: echo "Hi World!"
  second-job: 
    runs-on: ubuntu-latest
    steps:
      - name: step-two
        run: echo "CI-CD with github actions"